### PR TITLE
Create font_to_svg

### PR DESCRIPTION
**Pull request by willzyba**
Cleaned up code, so everything is within a class. Removed most of the debug statements. Optimised the creation of SVG paths, so the code is quicker and produces smaller output"
[master 3972238] Cleaned up code, so everything is within a class. Removed most of the debug statements. Optimised the creation of SVG paths, so the code is quicker and produces smaller output

### CODE REVIEW

**Comment by donbright** [comment]
thanks for the pull request. is there any way you can break this down into smaller commits?

**Comment by willzyba** [comment]
Hi Don,

I wish I had the time to do more, but attached is the latest version.

To be honest the minor change you can ignore, these include:
  - We’ve changes the class names, but thats only to be consistent with our naming convention.
  - The function Box():
        CRectangleF Box() const
        {
            // http://www.freetype.org/freetype2/docs/tutorial/step2.html <http://www.freetype.org/freetype2/docs/tutorial/step2.html> 
            return CRectangleF( _gm.horiBearingX, _gm.horiBearingY - _gm.height,
                               _gm.width ,
                               _gm.height );
        }
  - where we use our cross-platform version of the Microsoft RectangleF container, which is simply (left, top, width, height). Its essentially identical 

The main change is:
  - We removed any globally defined functions and variables. You had a standalone function that generated the SVG outlines, which we’ve folded into the class function outline().\
  - We’ve added a series of const functions to retrieve key attributes of the Font and Glyphs. You could ignore these, but they make the containers a lot easier to use.
  - I’ve trimmed down the number of class variables - they weren’t needed, especially with introduction of the helper functions.
  - We’ve more or less completely rewritten outline() using your original code as an ‘outline'. Its faster, hopefully simpler to understand, and also uses (when appropriate) the SVG ‘H’ and ‘V’ path attributes. I’d aim to do more work on this, for example consider using relative path definitions, and for bezier curves with two sets of control points I believe we can use the SVG ‘C’ option (though I couldn’t get it to work) or the ’T’ option, which simply extends a previous bezier using a mirror of its control point.

Anyways, many thanks for your original effort, its saved me many hours digging through FreeType documentation.

Best wishes

Will.

**Comment by donbright** [comment]
Thanks Will for the great work. 

I am not ready to replace the main .hpp file yet but ... id like to merge in alot of your stuff eventually. 

Im going to merge this into a separate file... maybe call it font_to_svg2.hpp and put a note in the README that it is there for future reference.

**Comment by donbright** [comment]
also please note i am marking the source file as modified by github username willzyba, as per the copyright license,

**Pull request merged**
